### ISSUE TITLE
FREQ: Add folding support for nested code and Aliasmask's RPEdit format?

### ISSUE THREAD

**Issue by Azhrei** [Daedeross/maptool-script.vscode#1]
Your "Planned Features" list includes an impressive set of functionality — I'm looking forward to it!

Something to add (?) to your list would be folding support so that nested code can be collapsed/expanded but also support for doing the same with Aliasmask's RPEdit format (which includes the ability to delineate multiple macros in a single source file, which makes it much easier to edit related UDFs as a single unit).

Thanks for sharing!

**Comment by Daedeross** [comment]
To my delight, VSCode supports folding for matching brackets, so [code: { ... }] sections and the like should be fold-able already. I think that's out of the box, but maybe it's from a setting or other extension I have somewhere?

I'll have to look into that RPEdit format. Adding folding to that should be doable, but may have to wait till I get more semantic features under my belt.

I haven't set up proper issue labels and templates in this repo yet, so I'll update this when I get around to that.

**Comment by Daedeross** [comment]
So looks like folding is auto-calculated by default by looking at indentation, which I always follow, so that's why it is working for me. In `language-configuration.json` one can add a single pair of begin/end Regexes for additional folding, for anything more complicated one needs to implement a `FoldingRangeProvider` which will likely require more semantic support.
I added FoldingRangeProvider to the roadmap.

RPEdit folding is implemented using regexes and will be supported next version.
